export const adminCopy = {
  metadata: {
    title: "走马村运营后台",
    description: "走马村 AIGC 云脑与运营后台。",
  },
  shell: {
    brand: "走马村运营后台",
    subtitle: "AIGC Cloud Brain",
    activeModule: "反馈管理",
    reserved: "预留",
    refresh: "刷新",
    empty: "暂无反馈工单",
    apiHint: "当前读取前台 /api/v1/feedback，工单已接入数据库持久化。",
  },
  menu: [
    { key: "dashboard", label: "云脑总览", status: "active" },
    { key: "feedback", label: "反馈管理", status: "active" },
    { key: "nodes", label: "节点管理", status: "active" },
    { key: "orders", label: "消费订单", status: "active" },
    { key: "reports", label: "运营日报", status: "active" },
    { key: "infrastructure", label: "设施调度", status: "active" },
    { key: "settings", label: "系统设置", status: "active" },
  ],
  nodeNameMap: {
    "visitor-center": "游客中心",
    "waypoints.visitorCenter": "游客中心",
    "taojiawan": "陶家湾",
    "waypoints.taojiawan": "陶家湾",
    "ancient-road": "走马岭古道",
    "waypoints.ancientRoad": "走马岭古道",
    "indoor-story": "室内古道故事点",
    "waypoints.indoorStory": "室内古道故事点",
    "shaded-ancient-road": "树荫古道短线",
    "waypoints.shadedAncientRoad": "树荫古道短线",
    "lychee-garden": "荔枝园",
    "waypoints.lycheeGarden": "荔枝园",
    "food-classroom": "食育课堂",
    "waypoints.foodClassroom": "食育课堂",
    "tree-adoption": "认养树区",
    "waypoints.treeAdoption": "认养树区",
    "waterfront-rest": "水岸休憩点",
    "waypoints.waterfrontRest": "水岸休憩点",
    "resilience-workshop": "韧性工坊",
    "waypoints.resilienceWorkshop": "韧性工坊",
    "ridge-courtyard": "岭上院落",
    "waypoints.ridgeCourtyard": "岭上院落",
    "village-meal": "乡宴餐点",
    "waypoints.villageMeal": "乡宴餐点",
    "morning-farm": "晨间农事体验点",
    "waypoints.morningFarm": "晨间农事体验点",
    "ancient-road-core": "古道叙事境",
    "scenes.detail.ancientRoad.title": "古道叙事境",
    "lychee-field-core": "荔田共生境",
    "scenes.detail.lycheeField.title": "荔田共生境",
    "resilience-valley-core": "韧谷研学境",
    "scenes.detail.resilienceValley.title": "韧谷研学境",
    "ridge-dwelling-core": "岭上共居境",
    "scenes.detail.ridgeDwelling.title": "岭上共居境",
  },
  stats: {
    total: "工单总数",
    open: "待处理",
    urgent: "高优先",
    rating: "平均满意度",
  },
  table: {
    title: "反馈工单",
    category: "分类",
    severity: "紧急程度",
    rating: "满意度",
    status: "状态",
    updatedAt: "更新时间",
  },
  detail: {
    title: "工单详情",
    content: "反馈内容",
    timeline: "处理记录",
    noteLabel: "处理备注",
    notePlaceholder: "记录本次处理动作，例如：已联系现场人员确认导视位置。",
    noSelection: "选择左侧工单查看详情。",
    loadFailed: "后台暂时无法读取反馈列表，请确认前台服务已启动。",
  },
  categories: {
    content: "内容讲解",
    service: "服务接待",
    facility: "设施导视",
    payment: "支付订单",
    other: "其他问题",
  },
  severities: {
    low: "普通记录",
    medium: "需要跟进",
    high: "影响体验",
    urgent: "现场紧急",
  },
  statuses: {
    submitted: "已提交",
    assigned: "已分派",
    processing: "处理中",
    resolved: "已解决",
    closed: "已关闭",
  },
  dashboard: {
    title: "云脑总览",
    todaySummary: "今日概览",
    hotNodes: "节点热度 TOP5",
    latestReport: "最新日报",
    activeAlerts: "活跃告警",
    visitors: "今日客流",
    revenue: "今日收入",
    orders: "今日订单",
    satisfaction: "平均满意度",
    noData: "数据收集中，请先接入 PresenceLog 和订单。",
    generateReport: "生成日报",
  },
  nodes: {
    title: "空间节点",
    detail: "节点详情",
    attractiveness: "吸引力分",
    safetyRisk: "安全风险分",
    visitors: "今日客流",
    avgDwell: "平均停留(分钟)",
    realm: "所属四境",
    nodeType: "节点类型",
    capacity: "容量",
    terrainRisk: "地形风险",
    watersideRisk: "近水风险",
    noData: "暂无节点数据。",
  },
  orders: {
    title: "统一订单",
    totalRevenue: "总收入",
    totalOrders: "总订单",
    avgOrder: "客单价",
    filterByType: "按类型",
    filterByNode: "按点位",
    allTypes: "全部类型",
    noData: "暂无订单数据。",
    types: {
      courtyard_booking: "院落预约",
      tree_adoption: "树木认养",
      ticket_order: "票务活动",
    },
  },
  reports: {
    title: "运营日报",
    generate: "生成日报",
    generating: "AI 正在生成...",
    actions: "行动建议",
    sections: "分析详情",
    noData: "暂无日报，点击上方按钮生成。",
    selectDate: "选择日期",
  },
  infrastructure: {
    title: "设施调度",
    sensors: "传感器读数",
    commands: "控制指令",
    pending: "硬件待接入",
    noSensorData: "传感器数据待接入。硬件就绪后通过 POST /api/v1/infrastructure/sensors 上报。",
    noCommandData: "暂无控制指令。传感器就绪后，决策引擎将自动生成灌溉/泄洪/火险建议。",
  },
  settings: {
    title: "系统设置",
    apiBase: "API 地址",
    dbStatus: "数据库",
    dbConnected: "已连接",
    envStatus: "环境变量",
    configured: "已配置",
    notConfigured: "未配置",
  },
  common: {
    loading: "正在加载...",
    error: "加载失败，请重试。",
    retry: "重试",
    noSelection: "选择左侧项目查看详情。",
    refresh: "刷新",
  },
  loading: "正在加载后台数据",
  errorTitle: "后台页面暂时没有加载成功",
  errorBody: "请稍后重试，或确认前台 API 服务是否已启动。",
  retry: "重新加载",
} as const
