export const adminCopy = {
  metadata: {
    title: "走马村运营后台",
    description: "走马村 AIGC 云脑与运营后台。",
  },
  shell: {
    brand: "走马村运营后台",
    subtitle: "AIGC Cloud Brain",
    activeModule: "反馈管理",
    reserved: "预留",
    refresh: "刷新",
    empty: "暂无反馈工单",
    apiHint: "当前读取前台 /api/v1/feedback，工单已接入数据库持久化。",
  },
  menu: [
    { key: "dashboard", label: "云脑总览", status: "active" },
    { key: "recommendations", label: "智策中心", status: "active" },
    { key: "map", label: "地图监控", status: "active" },
    { key: "feedback", label: "反馈管理", status: "active" },
    { key: "nodes", label: "节点管理", status: "active" },
    { key: "orders", label: "消费订单", status: "active" },
    { key: "trees", label: "树木管理", status: "active" },
    { key: "harvest", label: "采摘管理", status: "active" },
    { key: "activities", label: "活动管理", status: "active" },
    { key: "alerts", label: "告警中心", status: "active" },
    { key: "analytics", label: "交叉分析", status: "active" },
    { key: "villagers", label: "村民管理", status: "active" },
    { key: "farming", label: "农事日历", status: "active" },
    { key: "tasks", label: "任务调度", status: "active" },
    { key: "contentFactory", label: "内容工厂", status: "active" },
    { key: "aiAssistant", label: "AI 助手", status: "active" },
    { key: "devices", label: "设备管理", status: "active" },
    { key: "products", label: "农产品管理", status: "active" },
    { key: "reports", label: "运营日报", status: "active" },
    { key: "infrastructure", label: "设施调度", status: "active" },
    { key: "settings", label: "系统设置", status: "active" },
  ],
  nodeNameMap: {
    "visitor-center": "游客中心",
    "waypoints.visitorCenter": "游客中心",
    "taojiawan": "陶家湾",
    "waypoints.taojiawan": "陶家湾",
    "ancient-road": "走马岭古道",
    "waypoints.ancientRoad": "走马岭古道",
    "indoor-story": "室内古道故事点",
    "waypoints.indoorStory": "室内古道故事点",
    "shaded-ancient-road": "树荫古道短线",
    "waypoints.shadedAncientRoad": "树荫古道短线",
    "lychee-garden": "荔枝园",
    "waypoints.lycheeGarden": "荔枝园",
    "food-classroom": "食育课堂",
    "waypoints.foodClassroom": "食育课堂",
    "tree-adoption": "认养树区",
    "waypoints.treeAdoption": "认养树区",
    "waterfront-rest": "水岸休憩点",
    "waypoints.waterfrontRest": "水岸休憩点",
    "resilience-workshop": "韧性工坊",
    "waypoints.resilienceWorkshop": "韧性工坊",
    "ridge-courtyard": "岭上院落",
    "waypoints.ridgeCourtyard": "岭上院落",
    "village-meal": "乡宴餐点",
    "waypoints.villageMeal": "乡宴餐点",
    "morning-farm": "晨间农事体验点",
    "waypoints.morningFarm": "晨间农事体验点",
    "ancient-road-core": "古道叙事境",
    "scenes.detail.ancientRoad.title": "古道叙事境",
    "lychee-field-core": "荔田共生境",
    "scenes.detail.lycheeField.title": "荔田共生境",
    "resilience-valley-core": "韧谷研学境",
    "scenes.detail.resilienceValley.title": "韧谷研学境",
    "ridge-dwelling-core": "岭上共居境",
    "scenes.detail.ridgeDwelling.title": "岭上共居境",
  },
  stats: {
    total: "工单总数",
    open: "待处理",
    urgent: "高优先",
    rating: "平均满意度",
  },
  table: {
    title: "反馈工单",
    category: "分类",
    severity: "紧急程度",
    rating: "满意度",
    status: "状态",
    updatedAt: "更新时间",
  },
  detail: {
    title: "工单详情",
    content: "反馈内容",
    timeline: "处理记录",
    noteLabel: "处理备注",
    notePlaceholder: "记录本次处理动作，例如：已联系现场人员确认导视位置。",
    noSelection: "选择左侧工单查看详情。",
    loadFailed: "后台暂时无法读取反馈列表，请确认前台服务已启动。",
  },
  categories: {
    content: "内容讲解",
    service: "服务接待",
    facility: "设施导视",
    payment: "支付订单",
    other: "其他问题",
  },
  severities: {
    low: "普通记录",
    medium: "需要跟进",
    high: "影响体验",
    urgent: "现场紧急",
  },
  statuses: {
    submitted: "已提交",
    assigned: "已分派",
    processing: "处理中",
    resolved: "已解决",
    closed: "已关闭",
  },
  dashboard: {
    title: "云脑总览",
    todaySummary: "今日概览",
    hotNodes: "节点热度 TOP5",
    latestReport: "最新日报",
    activeAlerts: "活跃告警",
    visitors: "今日客流",
    revenue: "今日收入",
    orders: "今日订单",
    satisfaction: "平均满意度",
    noData: "数据收集中，请先接入 PresenceLog 和订单。",
    generateReport: "生成日报",
  },
  map: {
    title: "地图监控",
    subtitle: "空间节点实时态势",
    layer: "图层",
    heatLayer: "客流热力",
    riskLayer: "安全风险",
    spendLayer: "消费转化",
    activeNodes: "在线节点",
    latestVisitors: "实时客流",
    highRisk: "高风险节点",
    totalRevenue: "今日消费",
    noGeoData: "暂无可定位节点",
    noData: "地图数据收集中",
    visitors: "当前人数",
    attractiveness: "吸引力",
    safetyRisk: "安全风险",
    revenue: "消费收入",
    orders: "订单数",
    updatedAt: "最新上报",
  },
  nodes: {
    title: "空间节点",
    detail: "节点详情",
    attractiveness: "吸引力分",
    safetyRisk: "安全风险分",
    visitors: "今日客流",
    avgDwell: "平均停留(分钟)",
    realm: "所属四境",
    nodeType: "节点类型",
    capacity: "容量",
    terrainRisk: "地形风险",
    watersideRisk: "近水风险",
    noData: "暂无节点数据。",
  },
  orders: {
    title: "统一订单",
    totalRevenue: "总收入",
    totalOrders: "总订单",
    avgOrder: "客单价",
    filterByType: "按类型",
    filterByNode: "按点位",
    allTypes: "全部类型",
    noData: "暂无订单数据。",
    types: {
      courtyard_booking: "院落预约",
      tree_adoption: "树木认养",
      ticket_order: "票务活动",
      activity_booking: "活动预约",
      product_order: "农产品订单",
    },
  },
  reports: {
    title: "运营日报",
    generate: "生成日报",
    generating: "AI 正在生成...",
    actions: "行动建议",
    sections: "分析详情",
    noData: "暂无日报，点击上方按钮生成。",
    selectDate: "选择日期",
  },
  trees: {
    title: "树木管理",
    detail: "树木档案",
    careLogs: "养护日志",
    save: "保存档案",
    addLog: "录入养护日志",
    noData: "暂无树木数据。",
  },
  harvest: {
    title: "采摘预约",
    noData: "暂无采摘预约。",
    date: "预约日期",
    timeSlot: "时间段",
    guestCount: "人数",
    status: "状态",
  },
  activities: {
    title: "活动管理",
    noData: "暂无活动。",
    create: "创建活动",
    bookings: "预约列表",
  },
  alerts: {
    title: "告警中心",
    noData: "暂无告警。",
    type: "告警类型",
    severity: "等级",
    status: "状态",
    message: "内容",
    types: {
      night_linger: "夜间滞留",
      crowd: "拥堵",
      waterside: "临水风险",
      reverse_path: "逆向穿行",
      fire_risk: "火险",
      flood_risk: "雨洪风险",
      rainstorm: "暴雨预警",
      snowstorm: "雨雪预警",
      heat: "高温预警",
      wind: "大风预警",
      typhoon: "台风预警",
      device_offline: "设备离线",
      other: "其他天气预警",
    },
  },
  analytics: {
    title: "客流 × 消费分析",
    noData: "暂无当日数据。",
    peopleCount: "客流",
    revenue: "收入",
    orderCount: "订单",
    conversionRate: "转化率",
    roi: "人均收入",
  },
  villagers: {
    title: "村民管理",
    subtitle: "村民档案、技能标签与工作节点绑定",
    create: "新增村民",
    detail: "村民详情",
    name: "姓名",
    phone: "联系电话",
    skills: "技能标签",
    node: "工作节点",
    status: "状态",
    active: "在岗",
    inactive: "停用",
    save: "保存村民",
    saved: "村民已保存",
    saveFailed: "村民保存失败",
    noData: "暂无村民数据",
    noSelection: "选择左侧村民查看收益与任务概览。",
    earnings: "收益统计",
    earningsRanking: "收益排行",
    completedTasks: "完成任务",
    totalEarnings: "累计收益",
    monthlyTasks: "本月任务",
    monthlyEarnings: "本月收益",
    skillOptions: {
      cooking: "村宴烹饪",
      farming: "农事养护",
      guiding: "导览讲解",
      handicraft: "手作工坊",
      logistics: "物流协作",
    },
  },
  farming: {
    title: "农事日历",
    subtitle: "按节气组织农事、采摘、加工与节庆活动",
    create: "新增农事",
    solarTerm: "节气",
    activityTitle: "标题",
    description: "说明",
    activityType: "类型",
    startDate: "开始日期",
    endDate: "结束日期",
    treeSpecies: "树种",
    status: "状态",
    save: "保存农事",
    saved: "农事已保存",
    saveFailed: "农事保存失败",
    noData: "暂无农事日历数据",
    statuses: {
      upcoming: "未开始",
      active: "进行中",
      completed: "已完成",
    },
    activityTypes: {
      planting: "栽种",
      pruning: "修剪",
      fertilizing: "施肥",
      harvesting: "采摘",
      processing: "加工",
      festival: "节庆",
    },
  },
  tasks: {
    title: "任务调度",
    subtitle: "创建任务、分配村民，并跟踪状态与收益",
    create: "新建任务",
    detail: "任务详情",
    titleLabel: "任务名称",
    description: "任务说明",
    taskType: "任务类型",
    status: "状态",
    villager: "分配村民",
    node: "关联节点",
    scheduledDate: "计划日期",
    earnings: "任务收益",
    save: "保存任务",
    saved: "任务已保存",
    saveFailed: "任务保存失败",
    noData: "暂无任务数据",
    allTypes: "全部类型",
    allStatuses: "全部状态",
    unassigned: "未分配",
    statusOptions: {
      pending: "待分配",
      accepted: "已接受",
      in_progress: "进行中",
      completed: "已完成",
      cancelled: "已取消",
    },
    typeOptions: {
      farming: "农事养护",
      guiding: "导览讲解",
      logistics: "物流协作",
      maintenance: "设施维护",
      service: "接待服务",
    },
  },
  contentFactory: {
    title: "AI 内容工厂",
    subtitle: "生成导览词、活动脚本和社交文案",
    type: "内容类型",
    scene: "场景",
    activity: "活动",
    season: "季节",
    audience: "人群",
    generate: "生成内容",
    generating: "生成中...",
    result: "可编辑结果",
    copy: "复制结果",
    copied: "已复制",
    noSaveNotice: "结果不会保存，请复制后使用。",
    failed: "AI 生成失败，请检查模型配置或稍后重试。",
    types: {
      narration: "导览词",
      script: "活动脚本",
      social: "社交文案",
    },
  },
  aiAssistant: {
    title: "AI 助手",
    subtitle: "用自然语言查询云脑运营数据",
    placeholder: "例如：哪个节点转化率最低？",
    ask: "发送问题",
    asking: "分析中...",
    empty: "输入运营问题后，AI 会基于当前数据给出简短回答。",
    failed: "AI 助手暂时无法回答，请稍后重试。",
    question: "问题",
    answer: "回答",
  },
  devices: {
    title: "设备管理",
    subtitle: "IoT 设备台账与在线状态",
    create: "新增设备",
    deviceId: "设备编号",
    name: "设备名称",
    type: "设备类型",
    status: "状态",
    node: "绑定节点",
    location: "安装位置",
    lastSeenAt: "最后在线",
    latestReading: "最近读数",
    online: "在线",
    offline: "离线",
    unknown: "未上报",
    noData: "暂无设备数据",
    save: "保存设备",
    saved: "设备已保存",
    saveFailed: "设备保存失败",
  },
  products: {
    title: "农产品管理",
    subtitle: "产品台账与线下订单入口",
    create: "新增产品",
    name: "产品名称",
    category: "分类",
    description: "描述",
    price: "价格",
    unit: "单位",
    stockStatus: "库存状态",
    node: "消费节点",
    status: "状态",
    save: "保存产品",
    saved: "产品已保存",
    saveFailed: "产品保存失败",
    noData: "暂无产品数据",
    negotiable: "面议",
  },
  infrastructure: {
    title: "设施调度",
    sensors: "传感器读数",
    commands: "控制指令",
    pending: "硬件待接入",
    noSensorData: "传感器数据待接入。硬件就绪后通过 POST /api/v1/infrastructure/sensors 上报。",
    noCommandData: "暂无控制指令。传感器就绪后，决策引擎将自动生成灌溉/泄洪/火险建议。",
  },
  settings: {
    title: "系统设置",
    apiBase: "API 地址",
    dbStatus: "数据库",
    dbConnected: "已连接",
    envStatus: "环境变量",
    configured: "已配置",
    notConfigured: "未配置",
  },
  common: {
    loading: "正在加载...",
    error: "加载失败，请重试。",
    retry: "重试",
    noSelection: "选择左侧项目查看详情。",
    refresh: "刷新",
  },
  loading: "正在加载后台数据",
  errorTitle: "后台页面暂时没有加载成功",
  errorBody: "请稍后重试，或确认前台 API 服务是否已启动。",
  retry: "重新加载",
} as const
