export const adminCopy = {
  metadata: {
    title: "认养一棵树｜运营后台 Demo",
    description: "查看认养、养护任务、人工审核、认养权益和售后流程。",
  },
  shell: {
    brand: "走马村运营后台",
    subtitle: "认养与养护管理 Demo",
    activeModule: "反馈管理",
    reserved: "预留",
    refresh: "刷新",
    guestMode: "访客模式",
    adminMode: "管理员模式",
    adminLogin: "管理员登录",
    sessionExpired: "管理员会话已失效，当前为访客只读",
    writeLoginRequired: "登录管理员后可操作",
    empty: "暂无反馈工单",
    apiHint: "当前读取前台 /api/v1/feedback，工单已接入数据库持久化。",
  },
  nodeNameMap: {
    "visitor-center": "游客中心",
    "waypoints.visitorCenter": "游客中心",
    taojiawan: "陶家湾",
    "waypoints.taojiawan": "陶家湾",
    "ancient-road": "走马岭古道",
    "waypoints.ancientRoad": "走马岭古道",
    "indoor-story": "室内古道故事点",
    "waypoints.indoorStory": "室内古道故事点",
    "shaded-ancient-road": "树荫古道短线",
    "waypoints.shadedAncientRoad": "树荫古道短线",
    "lychee-garden": "荔枝园",
    "waypoints.lycheeGarden": "荔枝园",
    "food-classroom": "食育课堂",
    "waypoints.foodClassroom": "食育课堂",
    "tree-adoption": "认养树区",
    "waypoints.treeAdoption": "认养树区",
    "waterfront-rest": "水岸休憩点",
    "waypoints.waterfrontRest": "水岸休憩点",
    "resilience-workshop": "韧性工坊",
    "waypoints.resilienceWorkshop": "韧性工坊",
    "ridge-courtyard": "岭上院落",
    "waypoints.ridgeCourtyard": "岭上院落",
    "village-meal": "乡宴餐点",
    "waypoints.villageMeal": "乡宴餐点",
    "morning-farm": "晨间农事体验点",
    "waypoints.morningFarm": "晨间农事体验点",
    "ancient-road-core": "古道叙事境",
    "scenes.detail.ancientRoad.title": "古道叙事境",
    "lychee-field-core": "荔田共生境",
    "scenes.detail.lycheeField.title": "荔田共生境",
    "resilience-valley-core": "韧谷研学境",
    "scenes.detail.resilienceValley.title": "韧谷研学境",
    "ridge-dwelling-core": "岭上共居境",
    "scenes.detail.ridgeDwelling.title": "岭上共居境",
  },
  stats: {
    total: "工单总数",
    open: "待处理",
    urgent: "高优先",
    rating: "平均满意度",
  },
  table: {
    title: "反馈工单",
    category: "分类",
    severity: "紧急程度",
    rating: "满意度",
    status: "状态",
    updatedAt: "更新时间",
  },
  detail: {
    title: "工单详情",
    content: "反馈内容",
    timeline: "处理记录",
    noteLabel: "处理备注",
    notePlaceholder: "记录本次处理动作，例如：已联系现场人员确认导视位置。",
    noSelection: "选择左侧工单查看详情。",
    loadFailed: "后台暂时无法读取反馈列表，请确认前台服务已启动。",
  },
  categories: {
    content: "内容讲解",
    service: "服务接待",
    facility: "设施导视",
    payment: "支付订单",
    other: "其他问题",
  },
  severities: {
    low: "普通记录",
    medium: "需要跟进",
    high: "影响体验",
    urgent: "现场紧急",
  },
  statuses: {
    submitted: "已提交",
    assigned: "已分派",
    processing: "处理中",
    resolved: "已解决",
    closed: "已关闭",
  },
  dashboard: {
    title: "运营记录总览",
    todaySummary: "演示数据概览",
    hotNodes: "节点热度 TOP5",
    latestReport: "最新日报",
    activeAlerts: "活跃告警",
    visitors: "今日客流",
    revenue: "今日演示金额",
    orders: "今日演示订单",
    satisfaction: "平均满意度",
    noData: "还没有可展示的数据。接入 PresenceLog 和订单后再刷新页面。",
    generateReport: "生成日报",
  },
  map: {
    title: "地图监控",
    subtitle: "空间节点实时态势",
    layer: "图层",
    heatLayer: "客流热力",
    riskLayer: "安全风险",
    spendLayer: "消费转化",
    activeNodes: "在线节点",
    latestVisitors: "实时客流",
    highRisk: "高风险节点",
    totalRevenue: "今日消费",
    noGeoData: "还没有可定位节点，请先为节点补充区域位置。",
    noData: "地图还没有数据，请确认前台 API 和节点数据后刷新。",
    visitors: "当前人数",
    attractiveness: "吸引力",
    safetyRisk: "安全风险",
    revenue: "演示消费金额",
    orders: "演示订单数",
    updatedAt: "最新上报",
  },
  nodes: {
    title: "空间节点",
    detail: "节点详情",
    attractiveness: "吸引力分",
    safetyRisk: "安全风险分",
    visitors: "今日客流",
    avgDwell: "平均停留(分钟)",
    realm: "所属四境",
    nodeType: "节点类型",
    capacity: "容量",
    terrainRisk: "地形风险",
    watersideRisk: "近水风险",
    noData: "还没有节点数据，请先新增或导入节点。",
  },
  orders: {
    title: "演示订单",
    totalRevenue: "演示总金额",
    totalOrders: "演示订单数",
    avgOrder: "演示订单均价",
    filterByType: "按类型",
    filterByNode: "按点位",
    allTypes: "全部类型",
    noData: "还没有演示订单，可先从用户端创建一笔演示订单。",
    types: {
      courtyard_booking: "院落预约",
      tree_adoption: "树木认养",
      ticket_order: "票务活动",
      activity_booking: "活动预约",
      product_order: "农产品订单",
    },
  },
  reports: {
    title: "运营日报",
    generate: "生成日报",
    generating: "正在生成日报草稿...",
    actions: "行动建议",
    sections: "分析详情",
    noData: "还没有日报。选择日期后点击“生成日报”。",
    selectDate: "选择日期",
  },
  trees: {
    title: "树木管理",
    detail: "树木档案",
    careLogs: "养护记录",
    save: "保存档案",
    addLog: "添加养护记录",
    noData: "还没有树木档案。请先新增树木，再添加养护记录。",
  },
  harvest: {
    title: "采摘预约",
    noData: "还没有采摘预约。认养人提交预约后会显示在这里。",
    date: "预约日期",
    timeSlot: "时间段",
    guestCount: "人数",
    status: "状态",
  },
  activities: {
    title: "活动管理",
    noData: "还没有活动。点击“创建活动”添加第一场活动。",
    create: "创建活动",
    bookings: "预约列表",
  },
  alerts: {
    title: "告警中心",
    noData: "当前没有告警。接入传感器或产生现场事件后会显示在这里。",
    type: "告警类型",
    severity: "等级",
    status: "状态",
    message: "内容",
    types: {
      night_linger: "夜间滞留",
      crowd: "拥堵",
      waterside: "临水风险",
      reverse_path: "逆向穿行",
      fire_risk: "火险",
      flood_risk: "雨洪风险",
      rainstorm: "暴雨预警",
      snowstorm: "雨雪预警",
      heat: "高温预警",
      wind: "大风预警",
      typhoon: "台风预警",
      device_offline: "设备离线",
      other: "其他天气预警",
    },
  },
  analytics: {
    title: "客流 × 消费分析",
    noData: "当天还没有可分析的数据，请调整日期或先导入演示记录。",
    peopleCount: "客流",
    revenue: "演示金额",
    orderCount: "演示订单",
    conversionRate: "演示转化率",
    roi: "人均演示金额",
  },
  villagers: {
    title: "村民管理",
    subtitle: "村民档案、技能标签与工作节点绑定",
    create: "新增村民",
    detail: "村民详情",
    name: "姓名",
    phone: "联系电话",
    skills: "技能标签",
    node: "工作节点",
    status: "状态",
    active: "在岗",
    inactive: "停用",
    save: "保存村民",
    saved: "村民已保存",
    saveFailed: "村民档案没有保存成功，请检查填写内容和网络后重试",
    noData: "还没有村民档案。点击“新增村民”开始添加。",
    noSelection: "选择左侧村民查看演示任务金额与任务概览。",
    earnings: "演示任务金额",
    earningsRanking: "演示金额排序",
    completedTasks: "完成任务",
    totalEarnings: "累计演示金额",
    monthlyTasks: "本月任务",
    monthlyEarnings: "本月演示金额",
    skillOptions: {
      cooking: "村宴烹饪",
      farming: "农事养护",
      guiding: "导览讲解",
      handicraft: "手作工坊",
      logistics: "物流协作",
    },
  },
  farming: {
    title: "农事日历",
    subtitle: "按节气组织农事、采摘、加工与节庆活动",
    create: "新增农事",
    solarTerm: "节气",
    activityTitle: "标题",
    description: "说明",
    activityType: "类型",
    startDate: "开始日期",
    endDate: "结束日期",
    treeSpecies: "树种",
    status: "状态",
    save: "保存农事",
    saved: "农事已保存",
    saveFailed: "农事安排没有保存成功，请检查日期和填写内容后重试",
    noData: "还没有农事安排。点击“新增农事”添加第一条记录。",
    statuses: {
      upcoming: "未开始",
      active: "进行中",
      completed: "已完成",
    },
    activityTypes: {
      planting: "栽种",
      pruning: "修剪",
      fertilizing: "施肥",
      harvesting: "采摘",
      processing: "加工",
      festival: "节庆",
    },
  },
  tasks: {
    title: "养护任务",
    subtitle: "分配养护任务，并查看养护记录和审核进度",
    create: "新建养护任务",
    detail: "养护任务详情",
    titleLabel: "任务名称",
    description: "养护要求",
    taskType: "任务类型",
    status: "状态",
    villager: "分配村民",
    node: "关联节点",
    scheduledDate: "计划日期",
    earnings: "演示任务金额",
    save: "保存任务",
    saved: "养护任务已保存。列表已更新。",
    saveFailed: "养护任务没有保存成功，请检查填写内容和网络后重试",
    noData: "没有符合条件的养护任务。请调整筛选条件或新建任务。",
    allTypes: "全部类型",
    allStatuses: "全部状态",
    unassigned: "未分配",
    statusOptions: {
      pending: "待分配",
      accepted: "养护中",
      in_progress: "等待提交",
      submitted: "等待审核",
      rejected: "需要补充材料",
      resubmitted: "等待审核",
      approved: "审核已完成",
      settled: "结算已确认",
      exception_reported: "等待运营处理",
      overdue: "已超过截止时间",
      completed: "已完成",
      cancelled: "已取消",
    },
    typeOptions: {
      farming: "农事养护",
      guiding: "导览讲解",
      logistics: "物流协作",
      maintenance: "设施维护",
      service: "接待服务",
    },
    adoptionTask: "认养养护任务",
    careRecord: "养护记录",
    viewPhoto: "查看养护照片",
    reviewPlaceholder: "填写审核意见；退回时请写清缺少的照片或说明",
    approveReview: "确认记录合格",
    requestMore: "退回并说明缺少内容",
    rejectReasonRequired: "请先写明缺少什么，再退回这次养护记录。",
    approveSuccess: "这次养护记录已通过审核，后续权益和结算状态可以继续处理。",
    rejectSuccess: "这次养护记录已退回，村民补充材料后可以重新提交。",
    reviewFailed: "审核结果没有保存成功，请检查网络后重新提交。",
  },
  contentFactory: {
    title: "AI 文案草稿",
    subtitle: "AI 生成导览词、活动脚本和社交文案草稿，发布前需要人工检查",
    type: "内容类型",
    scene: "场景",
    activity: "活动",
    season: "季节",
    audience: "人群",
    generate: "生成内容",
    generating: "生成中...",
    result: "可编辑草稿",
    copy: "复制结果",
    copied: "已复制",
    noSaveNotice: "结果不会保存，请复制后使用。",
    failed: "文案草稿没有生成，请检查模型配置后重试，或改为手动填写。",
    types: {
      narration: "导览词",
      script: "活动脚本",
      social: "社交文案",
    },
  },
  aiAssistant: {
    title: "AI 查询助手",
    subtitle: "AI 只整理已审核制度和运营数据，最终处理方式由运营人员确认",
    knowledgeMode: "制度知识",
    operationsMode: "运营数据",
    knowledgePlaceholder: "例如：养护照片不清晰时应该怎么处理？",
    operationsPlaceholder: "例如：哪个节点转化率最低？",
    ask: "发送问题",
    asking: "分析中...",
    empty: "输入问题后，助手会整理已审核规则并列出原文引用，不会替代人工审核。",
    failed: "助手暂时无法回答。请稍后重试，或转交人工处理。",
    question: "问题",
    answer: "回答",
    citations: "原文引用",
    viewSource: "查看原文",
    documentVersion: "文档版本",
    allowedRoles: "适用角色",
    transfer: "转人工",
    transferred: "已创建人工处理记录",
    transferFailed: "暂时无法创建人工处理记录。",
    noCitation: "这条回答没有可核验引用，请不要直接用于审核或高风险操作。",
  },
  devices: {
    title: "设备管理",
    subtitle: "IoT 设备台账与在线状态",
    create: "新增设备",
    deviceId: "设备编号",
    name: "设备名称",
    type: "设备类型",
    status: "状态",
    node: "绑定节点",
    location: "安装位置",
    lastSeenAt: "最后在线",
    latestReading: "最近读数",
    online: "在线",
    offline: "离线",
    unknown: "未上报",
    noData: "还没有设备数据。点击“新增设备”录入第一台设备。",
    save: "保存设备",
    saved: "设备已保存",
    saveFailed: "设备没有保存成功，请检查设备编号和网络后重试",
  },
  products: {
    title: "农产品管理",
    subtitle: "产品台账与线下订单入口",
    create: "新增产品",
    name: "产品名称",
    category: "分类",
    description: "描述",
    price: "价格",
    unit: "单位",
    stockStatus: "库存状态",
    node: "消费节点",
    status: "状态",
    save: "保存产品",
    saved: "产品已保存",
    saveFailed: "产品没有保存成功，请检查名称、价格和网络后重试",
    noData: "还没有产品。点击“新增产品”录入第一项。",
    negotiable: "面议",
  },
  infrastructure: {
    title: "设施调度",
    sensors: "传感器读数",
    commands: "控制指令",
    pending: "硬件待接入",
    noSensorData:
      "传感器数据待接入。硬件就绪后通过 POST /api/v1/infrastructure/sensors 上报。",
    noCommandData:
      "还没有控制指令。传感器接入后，系统只生成灌溉、泄洪或火险建议，执行前需要人工确认。",
  },
  settings: {
    title: "系统设置",
    apiBase: "API 地址",
    dbStatus: "数据库",
    dbConnected: "已连接",
    envStatus: "环境变量",
    configured: "已配置",
    notConfigured: "未配置",
  },
  common: {
    loading: "正在加载...",
    error: "数据没有加载成功，请检查前台 API 和网络后重试。",
    retry: "重试",
    noSelection: "请先选择左侧项目，再查看详情或继续操作。",
    refresh: "刷新",
  },
  loading: "正在加载后台数据",
  errorTitle: "后台页面暂时没有加载成功",
  errorBody: "请稍后重试，或确认前台 API 服务是否已启动。",
  retry: "重新加载",
} as const
