import { prisma } from "../src/index"

const nodePositionsInZoumaRange: Record<string, { lat: number; lng: number }> = {
  "visitor-center": { lat: 29.8062, lng: 107.102 },
  taojiawan: { lat: 29.8075, lng: 107.1038 },
  "ancient-road": { lat: 29.8087, lng: 107.106 },
  "indoor-story": { lat: 29.8099, lng: 107.1082 },
  "shaded-ancient-road": { lat: 29.811, lng: 107.1105 },
  "lychee-garden": { lat: 29.807, lng: 107.1096 },
  "food-classroom": { lat: 29.8049, lng: 107.1081 },
  "tree-adoption": { lat: 29.8033, lng: 107.1066 },
  "waterfront-rest": { lat: 29.8014, lng: 107.1052 },
  "resilience-workshop": { lat: 29.7996, lng: 107.104 },
  "ridge-courtyard": { lat: 29.8061, lng: 107.1125 },
  "village-meal": { lat: 29.8043, lng: 107.114 },
  "morning-farm": { lat: 29.8026, lng: 107.1152 },
  "ancient-road-core": { lat: 29.8081, lng: 107.105 },
  "lychee-field-core": { lat: 29.8054, lng: 107.107 },
  "resilience-valley-core": { lat: 29.8008, lng: 107.1054 },
  "ridge-dwelling-core": { lat: 29.8053, lng: 107.1133 },
}

const nodes = [
  {
    slug: "visitor-center",
    nameKey: "waypoints.visitorCenter",
    realm: "ancient_road",
    nodeType: "entrance",
    capacity: 200,
    terrainRisk: 0.05,
    watersideRisk: 0,
    lat: 29.8512,
    lng: 106.321,
  },
  {
    slug: "taojiawan",
    nameKey: "waypoints.taojiawan",
    realm: "ancient_road",
    nodeType: "viewpoint",
    capacity: 80,
    terrainRisk: 0.2,
    watersideRisk: 0,
    lat: 29.853,
    lng: 106.3235,
  },
  {
    slug: "ancient-road",
    nameKey: "waypoints.ancientRoad",
    realm: "ancient_road",
    nodeType: "activity",
    capacity: 60,
    terrainRisk: 0.3,
    watersideRisk: 0.05,
    lat: 29.855,
    lng: 106.326,
    buildingAge: 80,
    buildingMaterial: "砖木",
    buildingFloors: 1,
    buildingArea: 60,
    buildingOrientation: "南",
    heritageStatus: "传统风貌建筑",
    lastRenovationAt: "1998",
    structuralCondition: "fair",
    aestheticCondition: "poor",
    functionalCondition: "fair",
    energyScore: 1.5,
    insulationQuality: "poor",
    ventilationQuality: "fair",
    solarPotential: "high",
    energyConsumptionEst: 120,
    greeneryCoverage: 0.15,
    waterPermeability: "low",
    biodiversityIndex: "low",
    microclimateZone: "湿热",
  },
  {
    slug: "indoor-story",
    nameKey: "waypoints.indoorStory",
    realm: "ancient_road",
    nodeType: "activity",
    capacity: 40,
    terrainRisk: 0,
    watersideRisk: 0,
    lat: 29.852,
    lng: 106.322,
  },
  {
    slug: "shaded-ancient-road",
    nameKey: "waypoints.shadedAncientRoad",
    realm: "ancient_road",
    nodeType: "viewpoint",
    capacity: 50,
    terrainRisk: 0.25,
    watersideRisk: 0,
    lat: 29.8545,
    lng: 106.325,
  },
  {
    slug: "lychee-garden",
    nameKey: "waypoints.lycheeGarden",
    realm: "lychee_field",
    nodeType: "activity",
    capacity: 100,
    terrainRisk: 0.1,
    watersideRisk: 0.1,
    lat: 29.849,
    lng: 106.319,
    buildingAge: 25,
    buildingMaterial: "砖混",
    buildingFloors: 2,
    buildingArea: 180,
    buildingOrientation: "东南",
    structuralCondition: "good",
    aestheticCondition: "fair",
    functionalCondition: "poor",
    energyScore: 2.5,
    insulationQuality: "fair",
    ventilationQuality: "poor",
    solarPotential: "medium",
    energyConsumptionEst: 200,
    greeneryCoverage: 0.1,
    waterPermeability: "low",
    biodiversityIndex: "low",
    microclimateZone: "湿热",
  },
  {
    slug: "food-classroom",
    nameKey: "waypoints.foodClassroom",
    realm: "lychee_field",
    nodeType: "activity",
    capacity: 40,
    terrainRisk: 0.05,
    watersideRisk: 0,
    lat: 29.8495,
    lng: 106.318,
  },
  {
    slug: "tree-adoption",
    nameKey: "waypoints.treeAdoption",
    realm: "lychee_field",
    nodeType: "activity",
    capacity: 30,
    terrainRisk: 0.05,
    watersideRisk: 0,
    lat: 29.848,
    lng: 106.317,
    greeneryCoverage: 0.8,
    waterPermeability: "high",
    biodiversityIndex: "high",
    microclimateZone: "林间",
  },
  {
    slug: "waterfront-rest",
    nameKey: "waypoints.waterfrontRest",
    realm: "resilience_valley",
    nodeType: "rest",
    capacity: 60,
    terrainRisk: 0.1,
    watersideRisk: 0.5,
    lat: 29.847,
    lng: 106.315,
    buildingAge: 15,
    buildingMaterial: "钢筋混凝土",
    buildingFloors: 1,
    buildingArea: 40,
    structuralCondition: "good",
    aestheticCondition: "fair",
    functionalCondition: "fair",
    energyScore: 3,
    greeneryCoverage: 0.25,
    waterPermeability: "medium",
    biodiversityIndex: "medium",
    microclimateZone: "滨水",
  },
  {
    slug: "resilience-workshop",
    nameKey: "waypoints.resilienceWorkshop",
    realm: "resilience_valley",
    nodeType: "activity",
    capacity: 50,
    terrainRisk: 0.15,
    watersideRisk: 0.1,
    lat: 29.8465,
    lng: 106.313,
  },
  {
    slug: "ridge-courtyard",
    nameKey: "waypoints.ridgeCourtyard",
    realm: "ridge_dwelling",
    nodeType: "shop",
    capacity: 40,
    terrainRisk: 0.1,
    watersideRisk: 0,
    lat: 29.8525,
    lng: 106.33,
    buildingAge: 60,
    buildingMaterial: "夯土",
    buildingFloors: 2,
    buildingArea: 250,
    buildingOrientation: "南",
    heritageStatus: "历史建筑",
    lastRenovationAt: "2005",
    structuralCondition: "fair",
    aestheticCondition: "good",
    functionalCondition: "fair",
    energyScore: 1,
    insulationQuality: "poor",
    ventilationQuality: "good",
    solarPotential: "high",
    energyConsumptionEst: 250,
    greeneryCoverage: 0.4,
    waterPermeability: "high",
    biodiversityIndex: "high",
    microclimateZone: "山地",
  },
  {
    slug: "village-meal",
    nameKey: "waypoints.villageMeal",
    realm: "ridge_dwelling",
    nodeType: "shop",
    capacity: 80,
    terrainRisk: 0.05,
    watersideRisk: 0,
    lat: 29.8515,
    lng: 106.329,
    buildingAge: 55,
    buildingMaterial: "石砌+木屋架",
    buildingFloors: 1,
    buildingArea: 200,
    buildingOrientation: "东",
    structuralCondition: "poor",
    aestheticCondition: "poor",
    functionalCondition: "critical",
    energyScore: 1,
    insulationQuality: "poor",
    ventilationQuality: "poor",
    solarPotential: "high",
    energyConsumptionEst: 0,
    greeneryCoverage: 0.05,
    waterPermeability: "low",
    biodiversityIndex: "low",
    microclimateZone: "山地",
  },
  {
    slug: "morning-farm",
    nameKey: "waypoints.morningFarm",
    realm: "ridge_dwelling",
    nodeType: "activity",
    capacity: 30,
    terrainRisk: 0.15,
    watersideRisk: 0.05,
    lat: 29.8535,
    lng: 106.331,
  },
  {
    slug: "ancient-road-core",
    nameKey: "scenes.detail.ancientRoad.title",
    realm: "ancient_road",
    nodeType: "entrance",
    capacity: 150,
    terrainRisk: 0.1,
    watersideRisk: 0.1,
    lat: 29.851,
    lng: 106.32,
  },
  {
    slug: "lychee-field-core",
    nameKey: "scenes.detail.lycheeField.title",
    realm: "lychee_field",
    nodeType: "entrance",
    capacity: 120,
    terrainRisk: 0.05,
    watersideRisk: 0.15,
    lat: 29.8485,
    lng: 106.316,
  },
  {
    slug: "resilience-valley-core",
    nameKey: "scenes.detail.resilienceValley.title",
    realm: "resilience_valley",
    nodeType: "entrance",
    capacity: 100,
    terrainRisk: 0.1,
    watersideRisk: 0.2,
    lat: 29.846,
    lng: 106.312,
  },
  {
    slug: "ridge-dwelling-core",
    nameKey: "scenes.detail.ridgeDwelling.title",
    realm: "ridge_dwelling",
    nodeType: "entrance",
    capacity: 80,
    terrainRisk: 0.15,
    watersideRisk: 0,
    lat: 29.852,
    lng: 106.328,
  },
].map((node) => ({
  ...node,
  ...nodePositionsInZoumaRange[node.slug],
}))

export async function seedNodes() {
  for (const node of nodes) {
    await prisma.spaceNode.upsert({
      where: { slug: node.slug },
      create: node,
      update: {
        nameKey: node.nameKey,
        realm: node.realm,
        nodeType: node.nodeType,
        capacity: node.capacity,
        terrainRisk: node.terrainRisk,
        watersideRisk: node.watersideRisk,
        lat: node.lat,
        lng: node.lng,
        buildingAge: node.buildingAge ?? null,
        buildingMaterial: node.buildingMaterial ?? null,
        buildingFloors: node.buildingFloors ?? null,
        buildingArea: node.buildingArea ?? null,
        buildingOrientation: node.buildingOrientation ?? null,
        heritageStatus: node.heritageStatus ?? null,
        lastRenovationAt: node.lastRenovationAt ?? null,
        structuralCondition: node.structuralCondition ?? null,
        aestheticCondition: node.aestheticCondition ?? null,
        functionalCondition: node.functionalCondition ?? null,
        energyScore: node.energyScore ?? null,
        insulationQuality: node.insulationQuality ?? null,
        ventilationQuality: node.ventilationQuality ?? null,
        solarPotential: node.solarPotential ?? null,
        energyConsumptionEst: node.energyConsumptionEst ?? null,
        greeneryCoverage: node.greeneryCoverage ?? null,
        waterPermeability: node.waterPermeability ?? null,
        biodiversityIndex: node.biodiversityIndex ?? null,
        microclimateZone: node.microclimateZone ?? null,
      },
    })
  }
}
