import { prisma } from "../src/index"

const nodePositionsInZoumaRange: Record<string, { lat: number; lng: number }> = {
  "visitor-center": { lat: 29.8062, lng: 107.102 },
  taojiawan: { lat: 29.8075, lng: 107.1038 },
  "ancient-road": { lat: 29.8087, lng: 107.106 },
  "indoor-story": { lat: 29.8099, lng: 107.1082 },
  "shaded-ancient-road": { lat: 29.811, lng: 107.1105 },
  "lychee-garden": { lat: 29.807, lng: 107.1096 },
  "food-classroom": { lat: 29.8049, lng: 107.1081 },
  "tree-adoption": { lat: 29.8033, lng: 107.1066 },
  "waterfront-rest": { lat: 29.8014, lng: 107.1052 },
  "resilience-workshop": { lat: 29.7996, lng: 107.104 },
  "ridge-courtyard": { lat: 29.8061, lng: 107.1125 },
  "village-meal": { lat: 29.8043, lng: 107.114 },
  "morning-farm": { lat: 29.8026, lng: 107.1152 },
  "ancient-road-core": { lat: 29.8081, lng: 107.105 },
  "lychee-field-core": { lat: 29.8054, lng: 107.107 },
  "resilience-valley-core": { lat: 29.8008, lng: 107.1054 },
  "ridge-dwelling-core": { lat: 29.8053, lng: 107.1133 },
}

const nodes = [
  {
    slug: "visitor-center",
    nameKey: "waypoints.visitorCenter",
    realm: "ancient_road",
    nodeType: "entrance",
    capacity: 200,
    terrainRisk: 0.05,
    watersideRisk: 0,
    lat: 29.8512,
    lng: 106.321,
  },
  {
    slug: "taojiawan",
    nameKey: "waypoints.taojiawan",
    realm: "ancient_road",
    nodeType: "viewpoint",
    capacity: 80,
    terrainRisk: 0.2,
    watersideRisk: 0,
    lat: 29.853,
    lng: 106.3235,
  },
  {
    slug: "ancient-road",
    nameKey: "waypoints.ancientRoad",
    realm: "ancient_road",
    nodeType: "activity",
    capacity: 60,
    terrainRisk: 0.3,
    watersideRisk: 0.05,
    lat: 29.855,
    lng: 106.326,
  },
  {
    slug: "indoor-story",
    nameKey: "waypoints.indoorStory",
    realm: "ancient_road",
    nodeType: "activity",
    capacity: 40,
    terrainRisk: 0,
    watersideRisk: 0,
    lat: 29.852,
    lng: 106.322,
  },
  {
    slug: "shaded-ancient-road",
    nameKey: "waypoints.shadedAncientRoad",
    realm: "ancient_road",
    nodeType: "viewpoint",
    capacity: 50,
    terrainRisk: 0.25,
    watersideRisk: 0,
    lat: 29.8545,
    lng: 106.325,
  },
  {
    slug: "lychee-garden",
    nameKey: "waypoints.lycheeGarden",
    realm: "lychee_field",
    nodeType: "activity",
    capacity: 100,
    terrainRisk: 0.1,
    watersideRisk: 0.1,
    lat: 29.849,
    lng: 106.319,
  },
  {
    slug: "food-classroom",
    nameKey: "waypoints.foodClassroom",
    realm: "lychee_field",
    nodeType: "activity",
    capacity: 40,
    terrainRisk: 0.05,
    watersideRisk: 0,
    lat: 29.8495,
    lng: 106.318,
  },
  {
    slug: "tree-adoption",
    nameKey: "waypoints.treeAdoption",
    realm: "lychee_field",
    nodeType: "activity",
    capacity: 30,
    terrainRisk: 0.05,
    watersideRisk: 0,
    lat: 29.848,
    lng: 106.317,
  },
  {
    slug: "waterfront-rest",
    nameKey: "waypoints.waterfrontRest",
    realm: "resilience_valley",
    nodeType: "rest",
    capacity: 60,
    terrainRisk: 0.1,
    watersideRisk: 0.5,
    lat: 29.847,
    lng: 106.315,
  },
  {
    slug: "resilience-workshop",
    nameKey: "waypoints.resilienceWorkshop",
    realm: "resilience_valley",
    nodeType: "activity",
    capacity: 50,
    terrainRisk: 0.15,
    watersideRisk: 0.1,
    lat: 29.8465,
    lng: 106.313,
  },
  {
    slug: "ridge-courtyard",
    nameKey: "waypoints.ridgeCourtyard",
    realm: "ridge_dwelling",
    nodeType: "shop",
    capacity: 40,
    terrainRisk: 0.1,
    watersideRisk: 0,
    lat: 29.8525,
    lng: 106.33,
  },
  {
    slug: "village-meal",
    nameKey: "waypoints.villageMeal",
    realm: "ridge_dwelling",
    nodeType: "shop",
    capacity: 80,
    terrainRisk: 0.05,
    watersideRisk: 0,
    lat: 29.8515,
    lng: 106.329,
  },
  {
    slug: "morning-farm",
    nameKey: "waypoints.morningFarm",
    realm: "ridge_dwelling",
    nodeType: "activity",
    capacity: 30,
    terrainRisk: 0.15,
    watersideRisk: 0.05,
    lat: 29.8535,
    lng: 106.331,
  },
  {
    slug: "ancient-road-core",
    nameKey: "scenes.detail.ancientRoad.title",
    realm: "ancient_road",
    nodeType: "entrance",
    capacity: 150,
    terrainRisk: 0.1,
    watersideRisk: 0.1,
    lat: 29.851,
    lng: 106.32,
  },
  {
    slug: "lychee-field-core",
    nameKey: "scenes.detail.lycheeField.title",
    realm: "lychee_field",
    nodeType: "entrance",
    capacity: 120,
    terrainRisk: 0.05,
    watersideRisk: 0.15,
    lat: 29.8485,
    lng: 106.316,
  },
  {
    slug: "resilience-valley-core",
    nameKey: "scenes.detail.resilienceValley.title",
    realm: "resilience_valley",
    nodeType: "entrance",
    capacity: 100,
    terrainRisk: 0.1,
    watersideRisk: 0.2,
    lat: 29.846,
    lng: 106.312,
  },
  {
    slug: "ridge-dwelling-core",
    nameKey: "scenes.detail.ridgeDwelling.title",
    realm: "ridge_dwelling",
    nodeType: "entrance",
    capacity: 80,
    terrainRisk: 0.15,
    watersideRisk: 0,
    lat: 29.852,
    lng: 106.328,
  },
].map((node) => ({
  ...node,
  ...nodePositionsInZoumaRange[node.slug],
}))

export async function seedNodes() {
  for (const node of nodes) {
    await prisma.spaceNode.upsert({
      where: { slug: node.slug },
      create: node,
      update: {
        nameKey: node.nameKey,
        realm: node.realm,
        nodeType: node.nodeType,
        capacity: node.capacity,
        terrainRisk: node.terrainRisk,
        watersideRisk: node.watersideRisk,
        lat: node.lat,
        lng: node.lng,
      },
    })
  }
}
