import type { RenovationPublicNode } from "@zouma/contracts"

export const renovationDemoNodes: RenovationPublicNode[] = [
  {
    nodeId: "demo-ancient-road",
    slug: "ancient-road-pavilion",
    nameKey: "古道驿亭",
    realm: "ancient_road",
    nodeType: "heritage_stop",
    demo: true,
    building: { age: 46, material: "砖木", floors: 1, area: 86, structuralCondition: "fair", energyScore: 2 },
    diagnosis: {
      id: "demo-diagnosis-1",
      urgency: "high",
      aiSummary: "传统砖木驿亭客流集中、围护结构热工性能弱，建议优先做低扰动节能修缮和动线分流。",
      issues: [],
      evidenceJson: { crowdStress: 0.92, feedbackRatio: 0.18, safetyScore: 3, energyScore: 2, ecologicalScore: 3, conversionRate: 0.04, sensorAnomalies: [], recentAlerts: 1 },
    },
    strategies: [
      { id: "demo-strategy-1", title: "传统民居围护结构节能改造", description: "以内保温、屋面隔热和门窗密封提升热舒适。", dimension: "energy", interventionType: "renovation", priority: "high", estimatedDuration: "3-6 周", estimatedCostRange: "¥800-1500/m²", expectedImpact: "降低夏季热压力，提升停留舒适度。" },
      { id: "demo-strategy-2", title: "弹性复合空间功能重组", description: "调整展示、休憩和等候关系，缓解入口拥堵。", dimension: "spatial", interventionType: "renovation", priority: "medium", estimatedDuration: "2-5 周", estimatedCostRange: "¥600-1200/m²" },
    ],
  },
  {
    nodeId: "demo-lychee-workshop",
    slug: "lychee-workshop",
    nameKey: "荔田工坊",
    realm: "lychee_field",
    nodeType: "workshop",
    demo: true,
    building: { age: 18, material: "砖混", floors: 1, area: 140, structuralCondition: "good", energyScore: 3 },
    diagnosis: {
      id: "demo-diagnosis-2",
      urgency: "medium",
      aiSummary: "工坊活动承载良好，但高峰时段热湿压力和功能混用明显，需要补足遮阳、通风和弹性分区。",
      issues: [],
      evidenceJson: { crowdStress: 0.78, feedbackRatio: 0.12, safetyScore: 4, energyScore: 3, ecologicalScore: 3, conversionRate: 0.08, sensorAnomalies: ["humidity_high"], recentAlerts: 0 },
    },
    strategies: [
      { id: "demo-strategy-3", title: "院落微气候调节", description: "通过遮阳棚、穿堂风和雨水花园改善半室外体验。", dimension: "energy", interventionType: "renovation", priority: "medium", estimatedDuration: "2-4 周", estimatedCostRange: "¥500-1000/m²" },
    ],
  },
  {
    nodeId: "demo-riverbank",
    slug: "longxi-riverbank",
    nameKey: "龙溪河岸",
    realm: "resilience_valley",
    nodeType: "waterside",
    demo: true,
    building: { age: 8, material: "景观构筑", floors: 1, area: 40, structuralCondition: "good", energyScore: 4 },
    diagnosis: {
      id: "demo-diagnosis-3",
      urgency: "high",
      aiSummary: "滨水空间近水风险和坡地冲刷风险偏高，优先处理护栏、防滑、生态护坡和亲水平台边界。",
      issues: [],
      evidenceJson: { crowdStress: 0.52, feedbackRatio: 0.22, safetyScore: 2, energyScore: 4, ecologicalScore: 2, conversionRate: null, sensorAnomalies: [], recentAlerts: 2 },
    },
    strategies: [
      { id: "demo-strategy-4", title: "滨水生态护坡与亲水平台", description: "用生态护坡和安全亲水平台替代硬质边界。", dimension: "ecological", interventionType: "renovation", priority: "high", estimatedDuration: "4-8 周", estimatedCostRange: "¥800-1600/m" },
    ],
  },
  {
    nodeId: "demo-ridge-yard",
    slug: "ridge-courtyard",
    nameKey: "岭上合院",
    realm: "ridge_dwelling",
    nodeType: "courtyard",
    demo: true,
    building: { age: 62, material: "夯土", floors: 2, area: 220, structuralCondition: "fair", energyScore: 1 },
    diagnosis: {
      id: "demo-diagnosis-4",
      urgency: "high",
      aiSummary: "夯土合院年代较久，节能评分低，适合在保护院落格局的前提下进行内保温和屋面隔热。",
      issues: [],
      evidenceJson: { crowdStress: 0.48, feedbackRatio: 0.1, safetyScore: 3, energyScore: 1, ecologicalScore: 3, conversionRate: 0.06, sensorAnomalies: [], recentAlerts: 0 },
    },
    strategies: [
      { id: "demo-strategy-5", title: "传统民居围护结构节能改造", description: "尊重夯土外观，优先采用内侧低扰动节能构造。", dimension: "energy", interventionType: "renovation", priority: "high", estimatedDuration: "3-6 周", estimatedCostRange: "¥800-1500/m²" },
    ],
  },
  {
    nodeId: "demo-granary",
    slug: "abandoned-granary",
    nameKey: "废弃粮仓",
    realm: "ridge_dwelling",
    nodeType: "abandoned_building",
    demo: true,
    building: { age: 54, material: "砖木", floors: 1, area: 160, structuralCondition: "poor", energyScore: 1 },
    diagnosis: {
      id: "demo-diagnosis-5",
      urgency: "critical",
      aiSummary: "废弃粮仓结构与功能价值双低，但局部砖墙和木梁具备场所记忆价值，建议部分拆除和新旧嵌合。",
      issues: [],
      evidenceJson: { crowdStress: 0.2, feedbackRatio: 0.3, safetyScore: 1, energyScore: 1, ecologicalScore: 2, conversionRate: null, sensorAnomalies: [], recentAlerts: 3 },
    },
    strategies: [
      { id: "demo-strategy-6", title: "部分拆除与新旧嵌合", description: "保留老墙和木梁，拆除低价值破损部分，植入展售与茶歇空间。", dimension: "spatial", interventionType: "partial_demolish_rebuild", priority: "critical", estimatedDuration: "8-12 周", estimatedCostRange: "¥1800-3000/m²" },
    ],
  },
  {
    nodeId: "demo-lychee-clearance",
    slug: "lychee-forest-clearance",
    nameKey: "荔枝林间空地",
    realm: "lychee_field",
    nodeType: "vacant_site",
    demo: true,
    building: { age: 0, material: "空地", floors: 0, area: 260, structuralCondition: "good", energyScore: 4 },
    diagnosis: {
      id: "demo-diagnosis-6",
      urgency: "medium",
      aiSummary: "林间空地适合承担高峰分流和轻量公共服务，应控制体量并保留树阵生态。",
      issues: [],
      evidenceJson: { crowdStress: 1.18, feedbackRatio: 0.14, safetyScore: 4, energyScore: 4, ecologicalScore: 4, conversionRate: null, sensorAnomalies: [], recentAlerts: 0 },
    },
    strategies: [
      { id: "demo-strategy-7", title: "场地新建：填空式轻建筑", description: "新建低矮轻量驿站，补充休憩、卫生和展陈功能。", dimension: "spatial", interventionType: "new_construction", priority: "high", estimatedDuration: "6-10 周", estimatedCostRange: "¥1800-2600/m²" },
    ],
    sitePotentials: [
      { id: "demo-site-1", nodeId: "demo-lychee-clearance", locationName: "林缘北侧", locationLat: 23.12, locationLng: 113.22, siteArea: 120, suitabilityScore: 86, accessibilityScore: 82, viewScore: 78, ecologyImpactScore: 18, recommendedProgram: "游客驿站", formKeywords: ["低矮", "木构", "架空"], constraints: [], status: "proposed", createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
      { id: "demo-site-2", nodeId: "demo-lychee-clearance", locationName: "林下南侧", locationLat: 23.121, locationLng: 113.221, siteArea: 90, suitabilityScore: 78, accessibilityScore: 74, viewScore: 88, ecologyImpactScore: 24, recommendedProgram: "林下课堂", formKeywords: ["半室外", "可拆装"], constraints: [], status: "proposed", createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() },
    ],
  },
]
